- hosts: all
  tasks:
    - name: Main block
      block:
        - name: Git clone   # clone code
          ansible.builtin.git:
            repo: 'https://github.com/arjunadas/ansible_target.git'
            dest: /tmp/django
            clone: yes
            update: yes
            force: yes
          tags:
            - git_clone
            
        - name: set +x script
          file: 
            path: /tmp/django/script.sh
            mode: 0755
          tags: 
            - change_permissions            

        - name: Run script = create Dockerfile # это единственный шелл, он нужен для создания web странички
          shell: /bin/bash /tmp/django/script.sh
          tags: 
            - run_script 

        - name: Add an Apt signing key, uses whichever key is at the URL
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
          tags:
            - apt_key

        - name: Add Repo
          apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower}} stable"
            state: present
            update_cache: yes
          tags:
            - add_repo

        - name: Install soft #install soft
          apt:
            name: "{{ item }}"
            state: present
          loop:
            - curl
            - apt-transport-https
            - ca-certificates
            - software-properties-common
            - docker-ce
            - nginx
          tags:
            - install
            
        - name: Install docker-compose
          get_url:
            url : https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-Linux-x86_64
            dest: /usr/local/bin/docker-compose
            mode: 'u+x,g+x'
          tags:
            - install_dc


      become: yes
